### ISSUE TITLE
Q: How to debug registration handlers?

### ISSUE THREAD

**Issue by senshi-x** [voryx/RxThruwayClient#8]
I have trouble understanding this:

> If the Registration Handler throws an exception, thruway.error.invocation_exception is returned to the caller. If you would like to allow more specific error messages, you must throw a WampErrorException or, if using observable sequences that are returned from the RPC, you can onError a WampErrorException.

Where and how do I get to see if a RPC is causing an invocation_exception?
I tried
```
try {
    client->register('test', function($test) {
        failplz(); // Function does not exist anywhere so this should cause problems
        return;
    }
} catch (Thruway\WampErrorExceptio $e) {
    error_log_(print_r($e,true));
}
```
to no avail. Neither does anything happen when starting the client, nor does anything happen when I call the RPC from somewhere, I always end up with the barebone invocation_exception. An example would be very much appreciated, I'm fairly certain I'm just missing something obvious. First time dealing with ReactPHP (even more so Rx) either, so that makes me easy to confuse right now.

**Comment by mbonneau** [comment]
@WGPSenshi - That part of the README is saying that if your RPC throws an exception internally, an invocation error of type 'thruway.error.invocation_exception' will be sent back to the router (and then forwarded to the calling client as a call error).

Your try-catch is actually only going to catch exceptions that occur during the call to `register` (Which will most likely not throw because is just builds an `Observable` and returns it).

Incidentally, calling a nonexistent function in PHP 7+ throws an `Error` and not an `Exception`. It is still catchable though.

As far as the `WampErrorException`: this is used to give you greater control of the error message sent back to the calling client. You would actually need to throw this.

Here is an example:
```php
$client->register('test', function ($args) {
    try {
        failplz();
    } catch (Throwable $t) {
        throw new WampErrorException('my.custom.error.uri', ['some', 'custom', 'error', 'info']);
    }
})
```
Also, because this is an `Observable` based Rx library, `register` simple returns an `Observable`. For things to get going, you need to `subscribe`:
```php
$obs = $client->register('test', function ($args) {
    try {
        failplz();
    } catch (Throwable $t) {
        throw new WampErrorException('my.custom.error.uri', ['some', 'custom', 'error', 'info']);
    }
})
$obs->subscribe(/* you can get info about registration here if you want */);
```

**Comment by senshi-x** [comment]
Thank you, this makes a lot more sense to me now and helped me along greatly with dealing with these kind of issues!
Unrelated, but still have to say it:
Love the thruway project, you always seem to be on point with issues and sharing your vast knowledge, can't appreciate that enough.
Which is actually  one of the reasons I chose it for upgrading an existing web project that used a pure REST backend (Slim): Now AngularJS clients (AngularWAMP) talk to Thruway. Meanwhile, jakubkulhan/bunny's AsyncClient uses the same \EventLoop as Thruway's server client to deal with RabbitMQ, allowing me a lot more flexibility and immediateness, benefitting clients a lot: No more blocking requests with long requests, clients stay informed about progress, and clients can get notified about other clients' actions/updates. Plenty of opportunites arise! 😍👍
